apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knot
resources:
  - namespace.yaml
  - api.yaml
  - presence.yaml
  - attachments.yaml
  - push.yaml
  - delivery.yaml
  - router.yaml
  - gateway.yaml
  - web.yaml
  - gateway-autoscaling.yaml
  - network-policies.yaml
